/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Designer001: THREE.SkinnedMesh
    Cylinder034_1: THREE.Mesh
    Cylinder034_2: THREE.Mesh
    Cylinder035_1: THREE.Mesh
    Cylinder035_2: THREE.Mesh
    Cylinder036: THREE.Mesh
    Cylinder037: THREE.Mesh
    Plane042: THREE.Mesh
    Rhand: THREE.Mesh
    Cube031: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube031_3: THREE.Mesh
    Cube031_4: THREE.Mesh
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
    Plane014_3: THREE.Mesh
    Plane014_4: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Plane022: THREE.Mesh
    Cylinder023_1: THREE.Mesh
    Cylinder023_2: THREE.Mesh
    Cylinder024: THREE.Mesh
    Cylinder024_1: THREE.Mesh
    Cylinder033: THREE.Mesh
    Bone: THREE.Bone
    Bone001: THREE.Bone
  }
  materials: {
    ['FABRIC 1_FRONT_3500.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['FABRIC 1_FRONT_3500.003']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['FABRIC 1_FRONT_3491']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'ArmatureAction' | 'ArmatureAction.000' | 'ArmatureAction.003' | 'ArmatureAction.004' | 'HeadAction' | 'Cube.000Action.002' | 'EmptyAction.004'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/Designer.9.7.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
	useEffect(()=>{
		Object.keys(actions).forEach(action => {
       actions[action].play()
		})
	})
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[0, -0.05, 0]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone001} />
          <skinnedMesh name="Designer001" geometry={nodes.Designer001.geometry} material={materials['FABRIC 1_FRONT_3500.003']} skeleton={nodes.Designer001.skeleton} />
        </group>
        <group name="Empty003" position={[2, -9.01, 0.85]} rotation={[0.01, 0, 0]}>
          <group name="Cylinder034" position={[0.26, -0.57, -2.2]} rotation={[Math.PI / 2, 0, 0.11]}>
            <mesh name="Cylinder034_1" geometry={nodes.Cylinder034_1.geometry} material={materials.Material} />
            <mesh name="Cylinder034_2" geometry={nodes.Cylinder034_2.geometry} material={materials['Material.004']} />
          </group>
          <group name="Cylinder035" position={[0.26, -0.57, -2.2]} rotation={[Math.PI / 2, 0, 0.11]}>
            <mesh name="Cylinder035_1" geometry={nodes.Cylinder035_1.geometry} material={materials.Material} />
            <mesh name="Cylinder035_2" geometry={nodes.Cylinder035_2.geometry} material={materials['Material.004']} />
          </group>
          <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} position={[0.27, -0.51, -2.28]} rotation={[Math.PI / 2, 0, 0.11]} />
          <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials['Material.012']} position={[0.22, 2.68, -1.93]} rotation={[Math.PI / 2, 0, 0.11]} />
          <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials['Material.011']} position={[0.45, 2.65, -3.07]} rotation={[1.65, 0.19, -2.93]} />
        </group>
        <mesh name="Rhand" geometry={nodes.Rhand.geometry} material={materials['Material.008']} position={[-0.06, -1.85, 0.54]} rotation={[Math.PI, -1.33, Math.PI]} scale={[-1.59, -0.44, -0.47]} />
        <group name="Body_and_Desk">
          <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials.Material} />
          <mesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={materials['FABRIC 1_FRONT_3500.003']} />
          <mesh name="Cube031_2" geometry={nodes.Cube031_2.geometry} material={materials['Material.004']} />
          <mesh name="Cube031_3" geometry={nodes.Cube031_3.geometry} material={materials['FABRIC 1_FRONT_3500.003']} />
          <mesh name="Cube031_4" geometry={nodes.Cube031_4.geometry} material={materials['Material.007']} />
        </group>
        <group name="Head" position={[-0.01, 7.52, 1.82]} rotation={[-0.17, 0, 0]}>
          <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.004']} />
          <mesh name="Plane014_1" geometry={nodes.Plane014_1.geometry} material={materials.Material} />
          <mesh name="Plane014_2" geometry={nodes.Plane014_2.geometry} material={materials['Material.005']} />
          <mesh name="Plane014_3" geometry={nodes.Plane014_3.geometry} material={materials['Material.009']} />
          <mesh name="Plane014_4" geometry={nodes.Plane014_4.geometry} material={materials['Material.008']} />
        </group>
        <group name="Cube000" position={[3.14, 1.37, 0.35]} rotation={[1.57, 0.11, 0.01]}>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['FABRIC 1_FRONT_3491']} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['Material.008']} />
        </group>
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.006']} position={[-5.21, -7.61, -2.27]} rotation={[2.78, -0.31, 2.87]} />
        <group name="Cylinder022" position={[-4.28, -9.64, -0.94]} rotation={[Math.PI / 2, 0, -0.63]}>
          <mesh name="Cylinder023_1" geometry={nodes.Cylinder023_1.geometry} material={materials.Material} />
          <mesh name="Cylinder023_2" geometry={nodes.Cylinder023_2.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cylinder023" position={[-4.28, -9.64, -0.94]} rotation={[Math.PI / 2, 0, -0.63]}>
          <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.Material} />
          <mesh name="Cylinder024_1" geometry={nodes.Cylinder024_1.geometry} material={materials['Material.004']} />
        </group>
        <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={materials['Material.012']} position={[-4.13, -6.39, -0.71]} rotation={[Math.PI / 2, 0, -0.63]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Designer.9.7.glb')
